# Strings have to be enclosed in double quotes
StringLiterals:
  EnforcedStyle: double_quotes

UnusedMethodArgument:
  Enabled: false

TrivialAccessors:
  Enabled: false

# Allow %r{} syntax
RegexpLiteral:
  Enabled: false

GuardClause:
  Enabled: false

# I find modifiers not to be worth it most of the time
IfUnlessModifier:
  Enabled: false

# Hard limits are bad
MethodLength:
  Enabled: false

RaiseArgs:
  Enabled: false

SignalException:
  Enabled: false